# Generated by Django 4.2 on 2023-06-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionstudyapp', '0006_rename_commnet_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lionstudyapp',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
