# Generated by Django 4.2 on 2023-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionstudyapp', '0007_lionstudyapp_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lionstudyapp',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='lionstudyapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
